echo "hello good morning"
echo "Car requires maintenance."
echo "Car drives on the road."
echo "Engine powers the car."
echo "Car needs gas to run."
echo "Brakes stop the car."
echo "change done in car"
